import React from "react";
import Head from "next/head"; // use this for heads/ leave it alone for pages
import Image from "next/image"; // use this for images
import styles from "../styles/Home.module.scss";
import Link from "next/link"; // use this for links
import { MainBanner } from "../components";

export default function Home() {
  return (
    <div>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main> */}
        {/* use this type of  class name the hello_header exists in your style sheet*/}
        {/* <h1 className={styles.hello_header}>HELLO</h1> */}
        {/* this is an example of how to use nested stylinggit remote rm upstream */}
        {/* <div className={styles.shawn}>
          <div className={styles.joy}></div>
        </div>
        <p>
          Get started by editing <code>pages/index.js</code>
        </p>
      </main>

      <footer></footer> */}

      <MainBanner/>
    </div>
  );
}
